### PR TITLE
#1859 – Save structure window: formats in drop-down list is not ordered

### PR DESCRIPTION
**Pull request by nanoblit**
## How the feature works? / How did you fix the issue?

Zrzut ekranu 2023-07-27 081726

## Check list
- [x] unit-tests written
- [ ] e2e-tests written
- [x] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [x] task status changed to "Code review"

### CODE REVIEW

**Comment by yuleicul** [comment]
This part is not the same as expected in the issue description. 
image
image


I think it's because the issue is outdated, could you please contact @Zhirnoff and confirm the latest design and update the issue description?

**Review by SashaGraves — APPROVED** [review]

**Comment by nanoblit** [comment]
@yuleicul  I renamed that mockStore file as you suggested and also renamed another one in other place for consistency. I left that one as js though, because typing it would cause an error because of the way its reducer is defined in another js file. I decided not to make a generic helper, because there were enough differences between just these two uses that it would add more unnecessary code on every use.

**Review by yuleicul — APPROVED** [review]
Thank you! Great job 👍

**Comment by Ustianskii** [comment]
Fixed. Tested on SA.
image
image

**Pull request merged**
