### PR TITLE
#2463 Rotation Tool: display predefined rotation angles and current angle

### LINKED ISSUE #2463: Rotation Tool: display predefined rotation angles and current angle
Enhance the rotation tool introduced in scope of #2090, so that user can see predefined rotation angles' marks as well as current rotation angle and can easier rotate the selection on needed angle. The rotation tool should work as follows:

1. Once user clicks the rotation handle and rotation mode is activated, the rounded rectangle should be replaced with a circle. Center of the circle should be in the center of rotation, circle diameter equal to the height of replaced rectangle. The rotation handle should not change its position while switching from selection to rotation mode and back.
2. The following predefined angles should be marked on the rotation circle: -90, -60, -45, -30, 0, 30, 45, 60, 90
3. Once user starts rotating the structure, the set of angles shown should always cover [-90 - +90] range relatively to the handle position, e.g. if the structure is rotated for 60 degrees, user should see -30, 0, 30, 45, 60, 90, 120, 135, 150
4. Current rotation angle should be displayed at starting position (0 degree). 
5. Once user releases left mouse button, the rotation mode is deactivated and selected fragment stays in its new position (rotated). Rotation circle should be replaced with rounded rectangle (handle on top). 

<p align="center">
hover-handle 
</p>

<p align="center">
rotation-start 
</p>

<p align="center">
rotation in progress
</p>

#184121704

### PR DESCRIPTION
**Pull request by yuleicul**
Closes #2463 

Note: 
1. According to UX design, the predefined degrees will be hidden if the radius is less than 65px.

rotation-2463-01

~~2. One **existing** implementation that needs attention is **15° is the smallest rotation degree**, which means the user cannot rotate like 13° or 34° etc.~~

~~[rotation-2463-02](https://user-images.githubusercontent.com/27288153/236608057-12083049-3bf8-421d-b8ff-3770e8cd00ea.gif)~~

### CODE REVIEW

**Comment by KonstantinEpam23** [comment]
Thanks for your PR @yuleicul, looks great!
Just some feedback we got on the changes:

1. When the rotation wheel goes near 180 degrees - only half of the angle marks are shown:
Screenshot 2023-05-09 at 00 58 19-upd

2. If a page is scrolled - the circle is drawn in the incorrect position. Steps to reproduce: 
 - have a canvas big enough to have a scroll bar
 - select a structure and rotate it
 - scroll the canvas and try to rotate the structure again
Screenshot 2023-05-09 at 01 08 41-upd

3. Can we please highlight the angle mark text for the one nearest to the cursor angle position.
Like so:
Screenshot 2023-05-09 at 01 22 40

4. This is more of just a nitpick, but sometimes the handle line and the circle line go a bit out of sync:
Screenshot 2023-05-09 at 01 33 10

5. This may only be reproducable on WIndows, but the rotation circle seems to stay on the canvas if Print Screen is pressed. Possible steps to reproduce (not tested):
 - select a structure and start rotating it
 - while the rotation circle is visible - press Print Screen to take a screenshot of part of the screen
 - after taking the screenshot -  continue rotating the figure
MicrosoftTeams-image (1)

**Comment by yuleicul** [comment]
@KonstantinEpam23 Thx for your feedback!
 
> 1. When the rotation wheel goes near 180 degrees - only half of the angle marks are shown:
> 
> Screenshot 2023-05-09 at 00 58 19-upd

I'm not sure if this is a bug because according to the requirement "_the set of angles shown should always cover [-90,+90] range relative to the handle position_",  positive 180 or 150 is not in the range of [-240, -60] when the current rotation degree is -150.

**Comment by KonstantinEpam23** [comment]
> I'm not sure if this is a bug because according to the requirement "_the set of angles shown should always cover [-90,+90] range relative to the handle position_", positive 180 or 150 is not in the range of [-150-90, -150+60] when the current rotation degree is -150.

I think in this case for example for 180 degrees it should treat the [-1, +1] range to result in [179, -179]
Basically always showing +/-90 degrees on both sides, something like this:
Screenshot 2023-05-09 at 09 43 39

**Comment by yuleicul** [comment]
> 3. Can we please highlight the angle mark text for the one nearest to the cursor angle position.
Like so:
> Screenshot 2023-05-09 at 01 22 40

I want to make sure how it works in the following cases, where the rotation degree doesn't overlap with the marks:
(note that the rotation step is 18)

image

I want to know your thoughts on which one is better, or maybe you have other ideas

**Comment by KonstantinEpam23** [comment]
> I want to make sure how it works in the following cases, where the rotation degree doesn't overlap with the marks: (note that the rotation step is 18)
> Let me know your thoughts @KonstantinEpam23 on which one is better, or maybe you have other ideas

We decided that for now we should only highlight the mark if it matches the current angle exactly. This should work well for the default situation when the rotation step is 15 degrees

**Comment by KonstantinEpam23** [comment]
@yuleicul found one more issue - when selecting all elements with Ctrl+A - the rotation wheel does not appear.

**Comment by yuleicul** [comment]
> 5. This may only be reproducable on WIndows, but the rotation circle seems to stay on the canvas if Print Screen is pressed. Possible steps to reproduce (not tested):
> 
> * select a structure and start rotating it
> * while the rotation circle is visible - press Print Screen to take a screenshot of part of the screen
> * after taking the screenshot -  continue rotating the figure
>   MicrosoftTeams-image (1)

My solution to this one is to make cursor 'not-allowed' after finishing screenshot. If you continue dragging, it will go back to its initial state.

rotation-2463-03

**Comment by KonstantinEpam23** [comment]
@yuleicul I think this solution is fine.

Also, one more small thing in addition to the ctrl+a issue - the box also does not appear when selecting while holding the shift key and clicking.

**Comment by yuleicul** [comment]
> @yuleicul I think this solution is fine.
> 
> Also, one more small thing in addition to the ctrl+a issue - the box also does not appear when selecting while holding the shift key and clicking.

The bounding box shows while holding and clicking from my side:
rotation-2463-shift

As you can see, if you are only clicking **bond** the box will not appear because stuff eligible for rotation must contain atoms.

**Comment by yuleicul** [comment]
One small mistake I made is that the **cross** rotated with structures. According to UX design, it shouldn't be rotated. Fixed.

**Comment by yuleicul** [comment]
@KonstantinEpam23 Thanks again for your detailed review! ❤️ I've fixed all above bugs you mentioned, please review again

**Review by KonstantinEpam23 — APPROVED** [review]

**Pull request merged**
