### PR TITLE
#3203 - Structure shifting to upper left corner during zoom operations

### LINKED ISSUE #2697: Add comments to different coordinate systems
**Background**
After zooming in or out the whole canvas, the positions of the cursor-following atom and the functional-group preview are incorrect.

Incorrect position of the cursor-following atom:

https://github.com/epam/ketcher/assets/27288153/3f55e4e5-9454-41e2-8c7f-3d9b107ef6f8

Incorrect position of functional group preview:

https://github.com/epam/ketcher/assets/27288153/e8dc73a7-ff3f-4160-b42d-33c595e25c5a

These bugs are somehow related to the coordinate conversion among different coordinate systems.

As we can see in `packages/ketcher-core/src/application/render/raphaelRender.js`, some functions such as`obj2view`, `view2obj`, and `page2obj` must be related to the coordinate conversion, but what they do is not clear to us.

**Solution**

1. To figure out what these coordinate systems exactly are.
2. Add comments or rename coordinate conversion functions to make them readable and clear to developers. 
3. Write a document if necessary.
4. Fix incorrect positions of cursor-following atom and functional-group preview

### LINKED ISSUE #2730: Refactoring request: Render "view2obj", "obj2view", "page2obj" refactoring
Currently, we have the `Render` class here: `packages/ketcher-core/src/application/render/raphaelRender.ts`.
**Problem:**
the naming of the methods "view2obj", "obj2view", "page2obj" is unclear.

### Proposal
`view2obj(...)` -> mark as **private** and rename to `convertCoordinatesDOMToCanvas(...)` 
`obj2view(...)` -> deprecate as unused.
`page2obj(...)` -> rename to `convertPageEventToCanvasVector(...)`

_NOTICE: Breaking change! Should be part of the major release._

### PR DESCRIPTION
**Pull request by yuleicul**
## New features

- Support to zoom in/out on the center of the canvas (by buttons and hotkeys)
- Support to zoom in/out on the position of the mouse (by `ctrl` + mouse wheel)
- Support to move the viewport by the mouse wheel and touchpad

## Extra fixes

- 🐞Fix the hand tool not moving the viewport sometimes
- 🐞Fix the wrong position of InfoPanel (the preview of Functional Group) after zooming in/out

## Tech Details

- Refactor the coordinate system to support viewBox-based zooming. See `CoordinateTransformation.ts`
  - Closes #2730
  - Closes #2697 
- Show `drawn` scrollbars (which are not real scrollbars) to indicate the relative positions. The advantage of a `drawn` or `fake` scrollbar is that you don't need to consider it into the coordinate system.

## Future enhancement

Just my personal proposal:

- Press the wheel button to use the hand tool, just like Excalidraw

## Checklist
- [x] unit-tests written (see `CoordinateTransformation.test.ts`)
- [x] e2e-tests written (see `zoom-changes.spec.ts` and `scroll-canvas.spec.ts`)
- [x] documentation updated 
  - User Guide:  see `Drawing operations/Zoom` 
  - Tech details: see `packages\ketcher-core\src\application\render\__docs__\ketcher-coordinates.png`
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [x] task status changed to "Code review"
- [x] reviewers are notified about the pull request

---
**Please feel free to skip reading the following content**
To the reviewers: 
I understand that seeing such a large amount of code changes can be overwhelming, but please don't be discouraged. The majority of these changes are updated snapshots of playwright tests, which failed due to minor differences in positioning. 
Thank you in advance for your review. I have personally reviewed all the changes twice, which I hope will provide some reassurance. Additionally, I apologize for not dividing the code into different commits based on refactoring or bug fixing, which would have made the review process more convenient.
You can click [HERE](https://github.com/epam/ketcher/pull/3412/files?file-filters%5B%5D=.js&file-filters%5B%5D=.jsx&file-filters%5B%5D=.less&file-filters%5B%5D=.ts&file-filters%5B%5D=.tsx&show-deleted-files=true&show-viewed-files=true
) to review the changed files without the inclusion of the massive snapshots.

### CODE REVIEW

**Comment by ViktoriaTkacheva** [comment]
1. When moving the viewport with the mouse wheel or the touchpad, the preview of the Template or the atom, that is under the mouse cursor moves along with the rest of the structures on the canvas. If moving the mouse sharply, the preview returns under the cursor  


https://github.com/epam/ketcher/assets/139227567/77f7e691-8deb-4133-a23e-f35fc1653c5b


https://github.com/epam/ketcher/assets/139227567/c21f6801-1401-4183-a5c6-0d60921c10e2

2. When zooming in or zooming out all elements on the canvas, the preview of the Functional Group remains unchanged. When moving the viewport with the mouse wheel or the touchpad, the preview of the Functional Group remains in its original place


https://github.com/epam/ketcher/assets/139227567/a4fd4079-4c92-4370-a061-57a49181f97f

3. If zooming in or zooming out using the touchpad, the movements look very sharp


https://github.com/epam/ketcher/assets/139227567/e4731cec-1ace-4e32-b594-bf58354f1531

**Comment by yuleicul** [comment]
> 1. When moving the viewport with the mouse wheel or the touchpad, the preview of the Template or the atom, that is under the mouse cursor moves along with the rest of the structures on the canvas. If moving the mouse sharply, the preview returns under the cursor
> ......

@ViktoriaTkacheva Fixed. Thank you so much for uncovering them!

**Comment by Nitvex** [comment]
One more thing – it is possible to scroll structures, when you open edit dialog:
image

**Comment by yuleicul** [comment]
> One more thing – it is possible to scroll structures, when you open edit dialog: image
> 
> UPD: If structure is large enough, then scrollbars appear in current solution as well: image

Redirected to #3472

**Review by Nitvex — APPROVED** [review]

**Comment by Zhirnoff** [comment]
Pre-tested. Looks good!)

**Review by Zhirnoff — APPROVED** [review]

**Comment by yuleicul** [comment]
> 3. If zooming in or zooming out using the touchpad, the movements look very sharp
> 
>  2023-10-17_17h51_26.mp4


Redirect to #3485

**Pull request merged**
